# Generated by Django 6.0.1 on 2026-01-20 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'computer_games',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('administrator', 'Администратор'), ('player', 'Игрок')], default='player', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CatalogGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='shopapp.game')),
            ],
            options={
                'db_table': 'catalog_games',
            },
        ),
        migrations.CreateModel(
            name='GameCatalog',
            fields=[
                ('catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopapp', models.ManyToManyField(related_name='in_catalogs', through='shopapp.CatalogGame', to='shopapp.game')),
            ],
            options={
                'db_table': 'game_catalogs',
            },
        ),
        migrations.AddField(
            model_name='cataloggame',
            name='catalog',
            field=models.ForeignKey(db_column='catalog_id', on_delete=django.db.models.deletion.CASCADE, to='shopapp.gamecatalog'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerFavoriteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='shopapp.game')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='shopapp.player')),
            ],
            options={
                'db_table': 'player_favorite_games',
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='favorite_games',
            field=models.ManyToManyField(related_name='favorited_by', through='shopapp.PlayerFavoriteGame', to='shopapp.game'),
        ),
        migrations.AlterUniqueTogether(
            name='cataloggame',
            unique_together={('catalog', 'game')},
        ),
    ]
